# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exposed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exposed.proto',
  package='org.dpppt.android.sdk.internal.backend.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rexposed.proto\x12,org.dpppt.android.sdk.internal.backend.proto\"y\n\x10ProtoExposedList\x12\x18\n\x10\x62\x61tchReleaseTime\x18\x01 \x01(\x03\x12K\n\x07\x65xposed\x18\x02 \x03(\x0b\x32:.org.dpppt.android.sdk.internal.backend.proto.ProtoExposee\",\n\x0cProtoExposee\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\x0f\n\x07keyDate\x18\x03 \x01(\x03\x62\x06proto3')
)




_PROTOEXPOSEDLIST = _descriptor.Descriptor(
  name='ProtoExposedList',
  full_name='org.dpppt.android.sdk.internal.backend.proto.ProtoExposedList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batchReleaseTime', full_name='org.dpppt.android.sdk.internal.backend.proto.ProtoExposedList.batchReleaseTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exposed', full_name='org.dpppt.android.sdk.internal.backend.proto.ProtoExposedList.exposed', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=184,
)


_PROTOEXPOSEE = _descriptor.Descriptor(
  name='ProtoExposee',
  full_name='org.dpppt.android.sdk.internal.backend.proto.ProtoExposee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.dpppt.android.sdk.internal.backend.proto.ProtoExposee.key', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyDate', full_name='org.dpppt.android.sdk.internal.backend.proto.ProtoExposee.keyDate', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=230,
)

_PROTOEXPOSEDLIST.fields_by_name['exposed'].message_type = _PROTOEXPOSEE
DESCRIPTOR.message_types_by_name['ProtoExposedList'] = _PROTOEXPOSEDLIST
DESCRIPTOR.message_types_by_name['ProtoExposee'] = _PROTOEXPOSEE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoExposedList = _reflection.GeneratedProtocolMessageType('ProtoExposedList', (_message.Message,), dict(
  DESCRIPTOR = _PROTOEXPOSEDLIST,
  __module__ = 'exposed_pb2'
  # @@protoc_insertion_point(class_scope:org.dpppt.android.sdk.internal.backend.proto.ProtoExposedList)
  ))
_sym_db.RegisterMessage(ProtoExposedList)

ProtoExposee = _reflection.GeneratedProtocolMessageType('ProtoExposee', (_message.Message,), dict(
  DESCRIPTOR = _PROTOEXPOSEE,
  __module__ = 'exposed_pb2'
  # @@protoc_insertion_point(class_scope:org.dpppt.android.sdk.internal.backend.proto.ProtoExposee)
  ))
_sym_db.RegisterMessage(ProtoExposee)


# @@protoc_insertion_point(module_scope)
